aquaticode/users/urls.py
from django.urls import path

from aquaticode.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views

from aquaticode.videos.views import landing_page, video_detail

urlpatterns = [
    path("", landing_page, name="landing-page"),
    path("<int:pk>/", video_detail, name="video-detail"),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

aquaticode/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    """
    Default custom user model for aquaticode.
    If adding fields that need to be filled at user signup,
    check forms.SignupForm and forms.SocialSignupForms accordingly.
    """

    #: First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)
    first_name = None  # type: ignore
    last_name = None  # type: ignore

    def get_absolute_url(self):
        """Get url for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

aquaticode/videos/models.py
from django.db import models


class Video(models.Model):
    video_file = models.FileField(upload_to="videos")

aquaticode/users/forms.py
from allauth.account.forms import SignupForm
from allauth.socialaccount.forms import SignupForm as SocialSignupForm
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserAdminChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserAdminCreationForm(admin_forms.UserCreationForm):
    """
    Form for User Creation in the Admin Area.
    To change user signup, see UserSignupForm and UserSocialSignupForm.
    """

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

        error_messages = {
            "username": {"unique": _("This username has already been taken.")}
        }


class UserSignupForm(SignupForm):
    """
    Form that will be rendered on a user sign up section/screen.
    Default fields will be added automatically.
    Check UserSocialSignupForm for accounts created from social.
    """


class UserSocialSignupForm(SocialSignupForm):
    """
    Renders the form when user has signed up using social accounts.
    Default fields will be added automatically.
    See UserSignupForm otherwise.
    """

aquaticode/videos/forms.py
from django import forms
from django.forms import FileInput

from .models import Video


class VideoUploadForm(forms.ModelForm):
    class Meta:
        model = Video
        fields = ["video_file"]
        widgets = {
            "video_file": FileInput(
                attrs={
                    "accept": "video/*",
                    "class": "form-control",
                }
            ),
        }


class VideoFiltersForm(forms.Form):
    brightness = forms.IntegerField(
        min_value=-100,
        max_value=100,
        initial=0,
        widget=forms.NumberInput(attrs={"type": "range", "min": -100, "max": 100}),
    )
    saturation = forms.IntegerField(
        min_value=-100,
        max_value=100,
        initial=0,
        widget=forms.NumberInput(attrs={"type": "range", "min": -100, "max": 100}),
    )
    blur = forms.IntegerField(
        min_value=0,
        max_value=100,
        initial=0,
        widget=forms.NumberInput(attrs={"type": "range", "min": 0, "max": 100}),
    )

aquaticode/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):

    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        assert (
            self.request.user.is_authenticated
        )  # for mypy to know that the user is authenticated
        return self.request.user.get_absolute_url()

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

aquaticode/videos/views.py
from django.core.exceptions import ValidationError
from django.core.files.base import ContentFile
from django.db import transaction
from django.http import HttpResponseServerError
from django.shortcuts import redirect, render
from django.views.generic import DetailView

from .forms import VideoFiltersForm, VideoUploadForm
from .models import Video
from .utils import apply_filters


def landing_page(request):
    if request.method == "POST":
        form = VideoUploadForm(request.POST, request.FILES)
        if form.is_valid():
            video = form.save()
            return redirect("video-detail", pk=video.id)
    else:
        form = VideoUploadForm()
    return render(request, "videos/landing_page.html", {"form": form})


class DetailVideoView(DetailView):
    model = Video

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context["form"] = VideoUploadForm()
        context["filters_form"] = VideoFiltersForm()
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()

        form = VideoFiltersForm(request.POST)
        if not form.is_valid():
            raise ValidationError("Filters not valid.")
        else:
            brightness = form.cleaned_data["brightness"]
            saturation = form.cleaned_data["saturation"]
            blur = form.cleaned_data["blur"]

            # Apply the filters to the video using the provided parameters
            file_content = apply_filters(
                video_path=self.object.video_file.path,
                brightness=brightness,
                saturation=saturation,
                blur=blur,
            )
            if not file_content:
                return HttpResponseServerError("Error encoding the video")

            with transaction.atomic():
                self.object.video_file.delete()
                self.object.video_file.save(
                    name="video.mp4", content=ContentFile(file_content)
                )

            context = self.get_context_data(object=self.object)
            context["filters_form"] = form
            return render(request, "videos/video_detail.html", context)


video_detail = DetailVideoView.as_view()

aquaticode/templates/base.html
{% load static i18n %}<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE }}">
<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>{% block title %}aquaticode{% endblock title %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="Behold My Awesome Project!">
  <meta name="author" content="Antonio Ercole De Luca">

  <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}">

  {% block css %}
  <!-- Latest compiled and minified Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <!-- Your stuff: Third-party CSS libraries go here -->

  <!-- This file stores project-specific CSS -->
  <link href="{% static 'css/project.css' %}" rel="stylesheet">
  {% endblock %}
  <!-- Le javascript
  ================================================== -->
  {# Placed at the top of the document so pages load faster with defer #}
  {% block javascript %}
  <!-- Bootstrap JS -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
          crossorigin="anonymous"></script>
  <!-- Your stuff: Third-party javascript libraries go here -->

  <!-- place project specific Javascript in this file -->
  <script defer src="{% static 'js/project.js' %}"></script>

  {% endblock javascript %}

</head>

<body>

<div class="container">

  {% if messages %}
  {% for message in messages %}
  <div class="alert alert-dismissible {% if message.tags %}alert-{{ message.tags }}{% endif %}">
    {{ message }}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
  {% endfor %}
  {% endif %}

  {% block content %}
  <p>Use this document as a way to quick start any new project.</p>
  {% endblock content %}

</div> <!-- /container -->

{% block modal %}{% endblock modal %}

{% block inline_javascript %}
{% comment %}
Script tags with only code, no src (defer by default). To run
with a "defer" so that you run inline code:
<script>
      window.addEventListener('DOMContentLoaded', () => {/* Run whatever you want */});

</script>
{% endcomment %}
{% endblock inline_javascript %}
</body>
</html>

aquaticode/templates/pages/about.html
{% extends "base.html" %}

aquaticode/templates/users/user_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}User: {{ object.username }}{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">

      <h2>{{ object.username }}</h2>
      {% if object.name %}
        <p>{{ object.name }}</p>
      {% endif %}
    </div>
  </div>

{% if object == request.user %}
<!-- Action buttons -->
<div class="row">

  <div class="col-sm-12">
    <a class="btn btn-primary" href="{% url 'users:update' %}" role="button">My Info</a>
    <a class="btn btn-primary" href="{% url 'account_email' %}" role="button">E-Mail</a>
    <!-- Your Stuff: Custom user template urls -->
  </div>

</div>
<!-- End Action buttons -->
{% endif %}

</div>
{% endblock content %}

aquaticode/templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
  <h1>{{ user.username }}</h1>
  <form class="form-horizontal" method="post" action="{% url 'users:update' %}">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn btn-primary">Update</button>
      </div>
    </div>
  </form>
{% endblock %}

aquaticode/templates/videos/landing_page.html
{% extends "base.html" %}

{% block content %}
<div class="mb-1">
  <nav class="navbar navbar-expand-md navbar-light bg-light">
    <div class="container">
      <div class="row">
        <div class="col-6">
          <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#uploadModal">
            Upload Video
          </button>
        </div>
        <div class="col-6">
          {% block download_video %}
          {% endblock download_video %}
        </div>
      </div>
    </div>
  </nav>
</div>

<div class="container mt-5">
  <div class="row ">
    <div class="col-8">
      {% block video %}
      {% endblock video %}
    </div>
    <div class="col-4">
      {% block effects %}
      {% endblock effects %}
    </div>
  </div>
</div>


<!-- Modal -->
<div class="modal fade" id="uploadModal" tabindex="-1" aria-labelledby="uploadModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="uploadModalLabel">Upload video</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      {% if form %}
      <form action="{% url 'landing-page' %}" method="post" enctype="multipart/form-data">

        <div class="modal-body">
          {% csrf_token %}
          {{ form.as_p }}
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary">Upload Video</button>
        </div>
      </form>
      {% endif %}
    </div>
  </div>
</div>

{% endblock content %}

aquaticode/templates/videos/video_detail.html
{% extends "videos/landing_page.html" %}


{% block video %}
<div class="embed-responsive embed-responsive-16by9">
  <video class="embed-responsive-item"
         src="{{ video.video_file.url }}" controls></video>
</div>
{% endblock video %}

{% block download_video %}
<a href="{{ video.video_file.url }}" download>
  <button type="button" class="btn btn-primary">
    Download video
  </button>
</a>
{% endblock download_video %}


{% block effects %}
<h5>Effects:</h5>
<form action="{% url 'video-detail' pk=video.pk%}" method="post">
  {% csrf_token %}
  {{ filters_form.as_p }}
  <button type="submit" class="btn btn-primary">Apply Filters</button>
</form>
{% endblock effects %}